services:
  db:
#    image: postgres:${POSTGRES_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_db
    build:
      context: .
      dockerfile: postgres/Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
        OPTIONAL_POSTGIS: ${OPTIONAL_POSTGIS}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${POSTGRES_CONFIG}:/etc/postgresql/postgresql.conf
      - db_data:/var/lib/postgresql/data/pgdata
    command: -c config_file=/etc/postgresql/postgresql.conf
    networks:
#      # Internal network
      - internal_network
    restart: unless-stopped

  odoo:
    container_name: ${COMPOSE_PROJECT_NAME}_odoo
    build:
      context: .
      dockerfile: odoo/Dockerfile
      args:
        ODOO_VERSION: ${ODOO_VERSION}
        OPTIONAL_WHISPER: ${OPTIONAL_WHISPER}
    ports:
      - "${ODOO_EXPOSED_PORT:-8069}:${ODOO_INTERNAL_PORT}"
      - "${ODOO_WEBSOCKET_EXPOSED_PORT:-8072}:${ODOO_WEBSOCKET_INTERNAL_PORT:-8072}"
    volumes:
      - ${ODOO_CONFIG}:/etc/odoo/odoo.conf
      - ${ODOO_ADDONS}:/mnt/extra-addons
      - ./enterprise:/mnt/enterprise
      - odoo_data:/var/lib/odoo
    environment:
      # Postgres container name
      - HOST=${COMPOSE_PROJECT_NAME}_db
      # Postgres user
      - USER=odoo
      # Postgres password
      - PASSWORD=odoo
      - DB_TEMPLATE=template0
    depends_on:
      - db
    #    command: "odoo -d master -u ps_factura_rozas"
    networks:
      # Internal network for containers
      - internal_network
    restart: unless-stopped

volumes:
  odoo_data:
    name: ${COMPOSE_PROJECT_NAME}_odoo_data
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data

networks:
  # Internal name with custom name for this environment
  internal_network:
    name: ${COMPOSE_PROJECT_NAME}_internal
    driver: bridge